### PR TITLE
Make sure quantization is used correctly

### PR DESCRIPTION
**Pull request by rasbt**
Adds quantization support to Python API.

(when reading one of your comments, @apaz-cli, I realized I totally forgot this)

### CODE REVIEW

**Comment by rasbt** [comment]
Not sure why the `test_generate_sequentially.py` test is failing with that 


```python
/usr/lib/python3.10/subprocess.py:526: CalledProcessError
----------------------------- Captured stdout call -----------------------------
repo_id: EleutherAI/pythia-14m
Setting HF_HUB_ENABLE_HF_TRANSFER=1
----------------------------- Captured stderr call -----------------------------
Using 2 devices
Loading model '/tmp/pytest-of-root/pytest-0/test_base_with_sequentially0/EleutherAI/pythia-14m/lit_model.pth' with {'name': 'pythia-14m', 'hf_config': {'name': 'pythia-14m', 'org': 'EleutherAI'}, 'scale_embeddings': False, 'block_size': 512, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 6, 'n_head': 4, 'head_size': 32, 'n_embd': 128, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'lm_head_bias': False, 'n_query_groups': 4, 'shared_attention_norm': False, 'norm_class_name': 'LayerNorm', 'norm_eps': 1e-05, 'mlp_class_name': 'GptNeoxMLP', 'gelu_approximate': 'none', 'intermediate_size': 512, 'rope_condense_ratio': 1, 'rope_base': 10000, 'n_expert': 0, 'n_expert_per_token': 0, 'rope_n_elem': 8}
Time to instantiate model: 0.01 seconds.
/__w/8/s/litgpt/generate/sequentially.py:212: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(str(checkpoint_path), mmap=True, map_location="cpu")
Time to load the model weights: 0.00 seconds.
Moving '_forward_module.transformer.h.0' to cuda:0
Moving '_forward_module.transformer.h.1' to cuda:0
Moving '_forward_module.transformer.h.2' to cuda:0
Moving '_forward_module.transformer.h.3' to cuda:1
Moving '_forward_module.transformer.h.4' to cuda:1
Moving '_forward_module.transformer.h.5' to cuda:1
Time to sequential-ize the model: 0.19 seconds.
Seed set to 1234
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

```

error. Seems unrelated.

**Comment by rasbt** [comment]
Everything is fine locally, maybe a machine issue.

**Comment by rasbt** [comment]
Has any of you seen this error before @awaelchli @Andrei-Aksionov ? I remember other cuda issues but I think never this one (but my brain is scattered at the moment and I maybe don't remember correctly)

**Comment by rasbt** [comment]
Based on a conversation with @Andrei-Aksionov this is also happening elsewhere might be a PyTorch daily issue. We will see tomorrow ...

**Comment by Andrei-Aksionov** [comment]
The current azure workflow uses a container with a dev version of pytorch (daily build).
I think it's better to switch to a stable version. Some issues that are present in the stable version might be fixed in the latest dev build and thus we can get a false positive CI result.
But users most likely use the latest stable version, so it's important to be aligned with them, I think.

**Comment by rasbt** [comment]
@Andrei-Aksionov I agree. I think the nightly dev build can be nice as a heads-up for future changes, but we actually need to be testing the version that is actually being used, and that is the latest stable version, which is installed via the `pyproject.toml`. Let's update the azure version to that. We can always test things on the dev version locally every few weeks or so. Changes in the dev version should not affect users until the stable version launches anyways.

**Pull request merged**
