### PR TITLE
The end of the `wip` branch

### PR DESCRIPTION
**Pull request by carmocca**
I'm too lazy to rebase the entire branch so I'll do a merge commit instead.

### CODE REVIEW

**Comment by awaelchli** [comment]
Can we consider doing a rebase+merge? I can help rebase it. We aren't that much diverged

**Comment by carmocca** [comment]
What for? Is it that bad to have a merge commit?

**Comment by carmocca** [comment]
But be my guest. Feel free to do open a new branch and try. I just thought it wasn't worth our time

**Comment by awaelchli** [comment]
```
git rebase main wip --interactive
```

worked for me. Only one conflict to resolve. And it will also drop [1096d5f](https://github.com/Lightning-AI/litgpt/pull/1127/commits/1096d5ff02214fe31d212d72386ba14eeff97af5) and [acb4718](https://github.com/Lightning-AI/litgpt/pull/1127/commits/acb4718d05f1c127ccbe6c4c3d1f8cfd6687b12e)

**Pull request closed without merging**
