### PR TITLE
Deprecate Support for Dolly, Nous-Hermes, Redpajama-Incite, Vicuna and H2O Danube Models.

### PR DESCRIPTION
**Pull request by ParagEkbote**
Addresses Issue #1401. I've removed support for the majority of the models, and the Danube2 model mentioned in the issue. I chose not to deprecate the Platypus model as it has some additional dependencies that need to be managed carefully.  Are there further files that need to be modified?

Please let me know, and I will make the necessary changes as required.

### CODE REVIEW

**Comment by ParagEkbote** [comment]
Could you please review the changes?

cc: @rasbt

**Comment by rasbt** [comment]
Thanks for the PR! This looks good to me. Let me CC @lantiga for a second look

**Comment by ParagEkbote** [comment]
Could you please review the changes?

cc: @lantiga

**Comment by ParagEkbote** [comment]
Could you please review the changes?

cc: @lantiga

**Comment by ParagEkbote** [comment]
Could you please review the changes?

cc: @lantiga

**Review by lantiga — APPROVED** [review]
LGTM, thanks for your patience @ParagEkbote

**Comment by TimeLessLing** [comment]
Hello, if I want to continue using Vicuna through litgpt, which branch should I choose?

**Comment by ParagEkbote** [comment]
@TimeLessLing version 0.5.4 has deprecated these models. You can install the previous or an older version by using the following command:

pip install litgpt==0.5.3

**Pull request merged**
