### PR TITLE
chore: more efficient seqlen

### PR DESCRIPTION
**Pull request by stillmatic**
save memory by only storing longest len / index of longest len

empirically this is ~10% faster (though I also think skipping this step might be helpful)

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks a lot for the contribution. I did a quick check comparing different methods for this and found that the original way is still fastest. Would you mind sharing how you measured the speed improvement?

```python
import numpy as np

num_entries = 100_000
max_length = 50_000

lengths = np.random.randint(1, max_length + 1, size=num_entries)
data = [{"input_ids": [0] * length} for length in lengths]


def get_longest_seq_length_v1(data):
     # find out the minimum max_seq_length required during fine-tuning (saves memory!)
     lengths = [len(d["input_ids"]) for d in data]
     longest_seq_length = max(lengths)
     longest_seq_ix = lengths.index(longest_seq_length)
     return longest_seq_length, longest_seq_ix


def get_longest_seq_length_v2(data):
     # find out the minimum max_seq_length required during fine-tuning (saves memory!)
     max_length = -1
     max_index = -1
     for i, d in enumerate(data):
         current_length = len(d["input_ids"])
         if current_length > max_length:
             max_length = current_length
             max_index = i
     return max_length, max_index


def get_longest_seq_length_v3(data):
    max_index, max_length = max(enumerate(data), key=lambda x: len(x[1]["input_ids"]))
    max_length = len(data[max_index]["input_ids"])
    return max_length, max_index
```

```
%timeit get_longest_seq_length_v1(data)
# 5.92 ms ± 99.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

```
%timeit get_longest_seq_length_v2(data)
# 6.21 ms ± 47 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

```
%timeit get_longest_seq_length_v3(data)
# 8.09 ms ± 42.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by stillmatic** [comment]
weird, thanks for that, I can repro on my end too. Maybe that was a fluke when I ran this code over an actual dataset, thinking more, `max` and `index` are likely deeply optimized in python and we spend more time in the `len` calculation anyways.

**Comment by rasbt** [comment]
Thanks for double-checking and offering to contribute!

**Comment by Andrei-Aksionov** [comment]
As far as I know, `len` method has time complexity of O(1), since every enumerator object keeps track of its length and store it in an attribute.
Just FYI.

**Comment by rasbt** [comment]
Nice insight! Learned something new!

**Pull request closed without merging**
