### PR TITLE
Update download_model_weights.md

### PR DESCRIPTION
**Pull request by eltociear**
specifiy -> specify

### CODE REVIEW

**Comment by thuan00** [comment]
hi Ikko,
im intrigued by your constant effort on fixing typos and providing japanese translations
i really like to understand your motivation or process of doing so too

your work is nice
however, personally i dont think there is much value in fixing trivial, harmless, infrequent typos
the same goes for translating (as people can use machine translation or just learn the international language gradually)

i think the world has many many more critical issues and we better prioritize more important work

let me know your views

**Comment by williamFalcon** [comment]
> hi Ikko, im intrigued by your constant effort on fixing typos and providing japanese translations i really like to understand your motivation or process of doing so too
> 
> your work is nice however, personally i dont think there is much value in fixing trivial, harmless, infrequent typos the same goes for translating (as people can use machine translation or just learn the international language gradually)
> 
> i think the world has many many more critical issues and we better prioritize more important work
> 
> let me know your views

@thuan00 i disagree here. Documentation and typos are super important. I appreciate the work @eltociear is doing here.

**Comment by Andrei-Aksionov** [comment]
Hey @thuan00 
I believe that every contribution counts, even if it's just a typo fix.
That is what makes an open source community great: everyone tries to help make the repo better in his own way.

**Comment by thuan00** [comment]
great views
i dont mean to under-appreciate or even see the work as valueless or to close the PR
contributions are welcome

what i mean is to understand and maybe suggest more important or valuable work
for example, if not humanity issues like climate change or poverty, if not the AI community's challenges and tasks, if, say, in the scope of this repo's typo issues, i can see quite a few more typos in many other files
maybe we can use some automated tool to correct typos holistically and effectively
maybe a commit with more typos being fixed

i am a bit worried for Ikko if his work is manual, time consuming
or triggered by things like OCD or driven by some other unhealthy motivation

sorry for taking things personally here
i can discuss this in a different channel

**Comment by lantiga** [comment]
@eltociear found the typo and sent a PR to fix it, we welcome this without reservations.

Every other consideration about the PR is out of scope, and any personal consideration about contributors themselves is definitely misplaced.

**Review by lantiga — APPROVED** [review]

**Comment by rasbt** [comment]
Thanks a lot for the PR @eltociear! Contributions like this help keeping projects neat & professional!

**Review by rasbt — APPROVED** [review]

**Comment by eltociear** [comment]
@williamFalcon  @Andrei-Aksionov  @lantiga @rasbt 
Thank you for accepting me!
Wish our relationship would last forever.

**Comment by thuan00** [comment]
alright @eltociear
nice to learn about your views
wish you well
hope to help in case you have any problem

btw, maybe a tool like this can be helpful for your interest in typos
https://crates.io/crates/typos
i saw it on a random PR
https://github.com/ggerganov/llama.cpp/pull/4354

**Comment by Tata0703** [comment]
@eltociear have you considered building an AI agent to automate this process?

**Comment by eltociear** [comment]
@Tata0703 I am not considering it at this time.

**Pull request merged**
