### PR TITLE
Fix kv-cache clearing in Python API and Serve

### LINKED ISSUE #1595: Apply kv-cache related memory improvements to litgpt serve
We also need to apply the memory-efficient kv-cache handling from #1590 and #1583 to `litgpt serve`

### PR DESCRIPTION
**Pull request by rasbt**
I think I found the culprit causing the weird results mentioned in #1595. I think the kv-cache was cleared incompletely. I will try out some more models, but it seems to look promising so far.

Fixes  #1595

### CODE REVIEW

**Comment by rasbt** [comment]
Ok, I am relatively sure now that this is it @awaelchli @Andrei-Aksionov !

Even Mathstral with the default `top_k=50` is now reasonable:

```python
from litgpt import LLM

llm = LLM.load("mistralai/mathstral-7B-v0.1")
llm.generate("What is 1+2?")
```

```
' 1+2 is equal to 3. The plus sign "+" is used to denote addition. So, when you add 1 and 2 together, you get 3.'
```

**Review by awaelchli — APPROVED** [review]
Sanity restored 👍 🚀

**Comment by Andrei-Aksionov** [comment]
Awesome that you've fixed that 🎉.

But for me it looks strange why it's even the case.

With 
```python
for block in self.model.transformer.h:
    block.attn.kv_cache.reset_parameters()
```

you just reset cache with zeros so you don't have to spend time/memory on recreating KV-cache.
And then in the forward pass the code uses token position indices to pick the corresponding records for keys and values.
So it shouldn't be a problem.

While with
```python
self.model.clear_kv_cache()
```

you just nuked it:
https://github.com/Lightning-AI/litgpt/blob/f80fefff6a5d127cc99c86be2d172415b49359d2/litgpt/model.py#L133-L136

Plus, I would understand why it could affect a generation that happened after the first one, since we could reuse an incorrect KV-cache, but from my understanding @rasbt had an issue with even the first generation call.

Strange, but maybe I'm missing something 🤔.

**Comment by rasbt** [comment]
You raise good points, and I really don't have a good explanation here.

**Pull request merged**
