### PR TITLE
Fix parameter naming issue with Mistral 7B v0.3

### PR DESCRIPTION
**Pull request by davmacario**
See #1431 and #1444.

After some investigation, I noticed two things:

1. The current download script (litgpg/scripts/download.py), when using safetensors models, does not download the file `model.safetensors.index.json` (which contains the mapping between the parameter name and the corresponding chunk); for Mistral 7B v0.3, this [file](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/blob/main/model.safetensors.index.json) contains the "correct" parameter names, i.e., the ones that LitGPT is able to convert without issues.
2. The issue about parameter naming happens when attempting the conversion from the file `consolidated.safetensors` (which gets 'converted' to `consolidated.bin` in download.py); turns out this file contains the model parameters saved with a different name (I suspect it was created from the original Mistral AI implementation), while the files `model-0000X-of-00003.safetensors` are created from the HF Transformers "MistralForCausalLM" class, so they have the "correct" weight names.

By downloading and using the `model.safetensors.index.json` file in the same way as the `pytorch_model.bin.index.json` file when working with '.bin' models from HF, the `consolidated.bin` file is not used (as the mapping is only necessary for the files `model-0000X-of-00003.safetensors`) and the model can be downloaded and converted without issues.

I was also considering preventing the download of `consolidated.safetensors` for what I said above.
The `huggingface_hub.snapshot_download` function used in download.py accepts the arg `ignore_patterns`, which I would use to ignore this file.

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks for the PR! When I understand correctly, the changes you are suggesting would only be in `litgpt/scripts/convert_hf_checkpoint.py`? Unfortunately, it looks like there were some accidents in your rebasing, so it looks like lots of duplicated changes got committed: There are currently more than 100 files changed. Would you mind rebasing again off of the recent main branch or maybe doing a fresh PR with just the files to be changed, e.g., `litgpt/scripts/convert_hf_checkpoint.py`? Let me know if you need help with that.

**Comment by rasbt** [comment]
Thanks! Btw GitHub now has a useful "sync fork" feature that you can use in your forked repo
Screenshot 2024-06-12 at 9 28 29 AM

**Comment by davmacario** [comment]
Yep! I believe it was the culprit of the extra commits, though, as it default synced my fork's branch to the main branch :/
I synced to this branch using remotes, and there were no issues.

I'm opening a new PR now!

**Comment by Andrei-Aksionov** [comment]
I prefer to sync my fork via GitHub actions CLI tool (gh) whenever I want to create a new branch.
Speeds up a process a little bit.

**Pull request closed without merging**
