### PR TITLE
Fix imports

### PR DESCRIPTION
**Pull request by rasbt**
Fixes an import issue Aaron was having.

### CODE REVIEW

**Review by awaelchli — APPROVED** [review]
@rasbt It would be nice if you could paste the error you got into the PR description. If the import order matters, it is often a sign of circular imports. And if that's the case, we should try to remove the circular dependency.

**Comment by rasbt** [comment]
Good point @awaelchli . In this case it was not the circular dependency but issues with relative imports:

```
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/server.py", line 15, in <module>
    from litgpt.generate.base import generate, next_token
  File "/teamspace/studios/this_studio/litgpt/litgpt/generate/base.py", line 17, in <module>
    from litgpt import GPT, Config, PromptStyle, Tokenizer
ImportError: cannot import name 'GPT' from 'litgpt' (unknown location)
```

**Comment by awaelchli** [comment]
But we don't have any relative imports LitGPT. Of course, the expectation is that the package is installed. Did the user not install the package? How could changing the import order fix something like that?

**Comment by rasbt** [comment]
Maybe @apaz-cli can provide more context here.

**Pull request merged**
