### PR TITLE
Use tinystories in `pretrain/debug.yaml`

### PR DESCRIPTION
**Pull request by carmocca**
Fixes https://github.com/Lightning-AI/litgpt/issues/1082#issuecomment-1989561205

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks! Are you planning to update the docs too?

**Comment by carmocca** [comment]
I didn't intend to. At least not as #1082 suggest which is a broader revisit of the pretaining tutorial

**Comment by rasbt** [comment]
No problem, just wanted to make sure that this doesn't accidentally close #1082, so we don't forget to address the docs separately. (I am just seeing though that it's `Fixes 1082 **(comment)**` so maybe the whole issue won't be closed upon merging. Seeing the **(comment)** the first time and I guess I learned something new ... again 😅

**Comment by carmocca** [comment]
It does close it. No we know haha

**Pull request merged**
