### PR TITLE
Preserve eos in encoding when max_seq_length = -1

### PR DESCRIPTION
**Pull request by sanderland**
Resolves the EOT issue in #1682

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks for the PR! 

@awaelchli  Since you have implemented the data utils and have much more experience with those than I do, would you mind taking a quick look if time permits?

**Comment by awaelchli** [comment]
It's fine to handle this edge case. Next step is to add a test here to complete the PR: https://github.com/Lightning-AI/litgpt/blob/main/tests/data/test_base.py

**Comment by sanderland** [comment]
> It's fine to handle this edge case. Next step is to add a test here to complete the PR: https://github.com/Lightning-AI/litgpt/blob/main/tests/data/test_base.py

Thanks for having a look, and will add unit tests.
If this is an edge case, I'd appreciate some insight into what went wrong to trigger it by copying my first example.
I see the config has `max_seq_length: Optional[int] = None` but then the SFTDataset uses `-1` instead as a convention, and I don't quite see how this gets converted. 
Maybe changing SFTDataset to use None as well would be best?

**Review by awaelchli — APPROVED** [review]

**Review by rasbt — APPROVED** [review]
Awesome, thanks for adding the tests to the  PR.

**Pull request merged**
