### PR TITLE
Remove redundant code in checkpoint conversion script

### PR DESCRIPTION
**Pull request by rasbt**
Remove some unused code in the HF conversion code to estimate file sizes

### CODE REVIEW

**Comment by Andrei-Aksionov** [comment]
There are other 2 comments in the #1534 that I've left.

**Comment by rasbt** [comment]
Thanks @Andrei-Aksionov, I saw one and added it, and the other one was the following?

> Maybe we could just retrieve the number of layers from the config file, monitor when the conversion script started working on another layer and use this as a signal to update the progress bar?

I like that idea and actually also attempted it, but in practice it would be a bit trickier and require more restructuring. Given that there are so many other important things to add to and improve in LitGPT, I thought it wouldn't be worth going down this rabbit hole now. The file-size based approach seems to get the job done well for now, what do you think?

**Comment by Andrei-Aksionov** [comment]
I like how you implemented it, so no need to do any changes.

**Review by Andrei-Aksionov — APPROVED** [review]

**Comment by rasbt** [comment]
Great, thanks 😊

**Pull request merged**
