### PR TITLE
Restore previous LitData assertions in tests

### PR DESCRIPTION
**Pull request by awaelchli**
Restores the assertions to what they were before updating LitData in #1573, by setting `drop_last=False` (default). To address comment from @carmocca https://github.com/Lightning-AI/litgpt/pull/1573#discussion_r1675794515

### CODE REVIEW

**Comment by rasbt** [comment]
For the tests, we can maybe use `drop_last=False` but during training, wouldn't it lead to instabilities/loss spikes then?

**Comment by awaelchli** [comment]
> wouldn't it lead to instabilities/loss spikes then?

I don't see how something like that should be possible just by dropping a single incomplete batch at the end of an epoch?

Setting `drop_last=False` can have a negative consequence when the model is compiled, because it would have to recompile when an input shape changes, which would be the case there. So in light of that, maybe we shouldn't merge this PR if we care about compiled models. But then let's leave the tests like they are and update the comment.

**Comment by rasbt** [comment]
This is just based on some empirical data when I did not use `drop_last=True` when running deep learning experiments in the past. But I think they were probably using BatchNorm so maybe there is no issue here.

**Comment by awaelchli** [comment]
I'll look into whether the current behavior with drop_last when shuffling in LitData is expected behavior and come back to https://github.com/Lightning-AI/litgpt/pull/1573#discussion_r1675794515

**Pull request closed without merging**
