### PR TITLE
Add automated benchmark table

### PR DESCRIPTION
**Pull request by awaelchli**
Replaces the table with numbers in `config_hub/finetune/README.md` with a table of automated benchmark numbers. They were produced using [this studio](https://lightning.ai/lightning-ai/studios/automated-benchmarks-for-litgpt) (internal only).

The table is larger than the previous because it includes all combinations of

```
Finetune config x Machine type
```
Only configurations that required more devices than available were filtered out. Included are also experiments running on a multi-GPU machine despite only running on 1 device (this was specifically requested). 
Only A10G and 4xA10G machine types are listed at the moment.

As requested, more columns will be added in the future with eval-harness results.

### CODE REVIEW

**Comment by Andrei-Aksionov** [comment]
@awaelchli Could you add an empty row between each model type as in [here](https://github.com/Lightning-AI/litgpt/blob/main/tutorials/resource-tables.md#finetuning-with-lora-on-1-gpu)? Otherwise it's a bit difficult to read the table.

**Comment by Andrei-Aksionov** [comment]
Interestingly enough, for small models like Phi-2 and TinyLlaMA QLoRA doesn't make a lot of sense.
For TinyLlaMA the VRAM consumption for QLoRA is even higher than for full fine-tuning 🤔.

**Review by rasbt — CHANGES_REQUESTED** [review]
I know it may look weird coming from € but it's \$0.7 not 0.7\$. It's a US convention. Could you update it?

**Comment by rasbt** [comment]
> Interestingly enough, for small models like Phi-2 and TinyLlaMA QLoRA doesn't make a lot of sense.
For TinyLlaMA the VRAM consumption for QLoRA is even higher than for full fine-tuning 🤔.

Yeah it's super weird. I remember discussing this here a while back when we observed it. Maybe the conversion overhead, I dunno. It's definitely nothing wrong with the benchmarks here.

**Review by rasbt — APPROVED** [review]
This looks nice. I was thinking we could add an asterisk to OOM. E.g., OOM\* and then below the table:

\*OOM = Out of memory

But we already explain it in the introduction

>  see the [Dealing with out-of-memory (OOM) errors](../../tutorials/oom.md) on lowering the me

So I think this should be sufficient.

**Pull request merged**
