### PR TITLE
Several improvements related to KVCache

### PR DESCRIPTION
**Pull request by mseeger**
Implements what is asked for in #1867.

- Ensure that `KVCache` buffers are only as large as `config.n_query_groups`
- Shrink buffers returned by `KVCache` to just cover `input_pos` entries
- Refactor child classes of `model.py` classes to avoid copy and paste

Also adding comments, docstrings here and there.

### CODE REVIEW

**Comment by mseeger** [comment]
I am interested in smart KV caches for memory-efficient inference.

**Comment by mseeger** [comment]
Hi @Andrei-Aksionov,

let me know what I should change. Indeed, I could split this into 3:
1. Refactor child classes ...
2. KV cache buffers
3. Shrink buffers

It is just that 1. is really needed for the other two.

I understand this single file argument. But maybe there should be a balance? In the end, you inherit code from `model.py` in the other modules `adapter.py`, ..., lots of it, just the constructors are not properly done. I just introduced some simple factory functions. Maybe I did too much OOP, but for me, the new state is simpler, since I immediately see where the differences are going from the base case to adapter, etc.

Another point: Why I am looking at LitGPT and not Hugging Face (a colleague pointed your project out to me) is because the structure is so much clearer. I can learn a lot about different models by immediately seeing what is common and what is different. In HF, this is next to impossible, because everything is copied for every new model.

**Comment by Andrei-Aksionov** [comment]
```text
let me know what I should change. Indeed, I could split this into 3:

1. Refactor child classes ...
2. KV cache buffers
3. Shrink buffers
```

Let's do #2 and #3 in two separate PRs for now.

-----


```text
... But maybe there should be a balance? ...
... since I immediately see where the differences are going from the base case to adapter, etc.
```

Here I agree. It's easier to see the difference between PEFT implementation and the base model, if we reuse unchanged parts of the code from the base model.
I'll think about it over the weekend.
Most likely we can do it in "baby steps", without touching the base model.py at first.

I would recommend to focus on #2 and #3 first.

-----

Another point: Why I am looking at LitGPT and not Hugging Face (a colleague pointed your project out to me) is because the structure is so much clearer. I can learn a lot about different models by immediately seeing what is common and what is different. In HF, this is next to impossible, because everything is copied for every new model.

So pleasant to hear it. Thanks 😊

**Comment by t-vi** [comment]
> Shrink buffers returned by KVCache to just cover input_pos entries

Note that depending on the attention implementation and its handling of masking this may or may not have the impact you have in mind.

**Comment by mseeger** [comment]
@t-vi I am subselecting the mask at the same time. But do you have anything else in mind?

**Comment by mseeger** [comment]
OK, I'll close this one and submit a new one, where I drop the refactoring of constructors of `model.py` classes.

**Pull request closed without merging**
