### PR TITLE
bump macos to m1

### PR DESCRIPTION
**Pull request by t-vi**
some discussion on #1724 

seems to run into segfaults. obviously, if anyone with a macbook or so could take over sorting things out, it would be supergood.

### CODE REVIEW

**Comment by Andrei-Aksionov** [comment]
Tried to run API tests locally on M3 chip and had no issues.
Unfortunately, I have no time to debug it. 
@rasbt all hope is on you.

P.S. Here is an interesting project: https://github.com/mxschmitt/action-tmate
Haven't tried it, but in theory it should allow you to connect to a runner and check what's what.

**Comment by t-vi** [comment]
So by commenting out the LLM imports, it makes the segfaults go away, but isn't a realistic option.
Also, tons of failing tests.

**Comment by rasbt** [comment]
It's a bit of a weird machine. The memory issues aside, I am also seeing

> FAILED tests/test_convert_lit_checkpoint.py::test_against_original_gemma_2[device0-dtype0-gemma-2-27b] - AssertionError: Tensor-likes are not close!
Mismatched elements: 305 / 5120000 (0.0%)
Greatest absolute difference: 1.7881393432617188e-05 at index (0, 13, 73469) (up to 1e-05 allowed)

It works perfectly fine locally on both my Macs on M1 and M3. I am also using macOS 14.

**Comment by rasbt** [comment]
Interestingly, it's not the LLM import that causes the segfault but something else in there. I will go through the functions one by one.

**Comment by rasbt** [comment]
I was able to isolate it, it's this one here that segfaults on the CI:

```
def test_llm_load_random_init(tmp_path):
     download_from_hub(repo_id="EleutherAI/pythia-14m", tokenizer_only=True, checkpoint_dir=tmp_path)

     torch.manual_seed(123)
     llm = LLM.load(
         model="pythia-160m",
         init="random",
         tokenizer_dir=Path(tmp_path/"EleutherAI/pythia-14m")
     )
```

Works fine locally though ...

**Comment by rasbt** [comment]
To narrow it down further, it only happens with the default settings, not when `distribute=None`. This means, it's something related to the code here:

https://github.com/Lightning-AI/litgpt/blob/a686b4069e020d31f6280196ec65c2cec737c70e/litgpt/api.py#L215-L239

Perhaps the MPS support in the CI has some issues. (Since it works fine locally.)

**Comment by rasbt** [comment]
@t-vi @Andrei-Aksionov 

Ah, so it does seem to be MPS related. I.e., changing 

```
     if torch.cuda.is_available(): 
         accelerator = "cuda" 
     elif torch.backends.mps.is_available(): 
         accelerator = "mps" 
     else: 
         accelerator = "cpu" 
```

to 

```
     if torch.cuda.is_available(): 
         accelerator = "cuda" 
     else: 
         accelerator = "cpu" 
```

will fix those tests on the the CI. My guess is that's it's something particular about the CI machine because it works fine locally on 2 of my Macs (+ also on Andrei's Mac). Maybe outdated drivers.

So let's just skip MPS-related tests on that machine.

**Comment by rasbt** [comment]
Ok, I left MPS disabled for the macos runner since it seems to have issues. Could be Fabric-related, driver-related or LitGPT-related (although it works fine locally). Let's merge this for now and revisit in a few weeks or months when the macos-15 machines are more readily available in workflows. Maybe their drivers are just old.

**Pull request merged**
